### ISSUE TITLE
@b4 のメンションがおかしい。

### ISSUE THREAD

**Issue by macinjoke** [cpslab/cpsbot#3]
<img width="1008" alt="2018-05-30 1 33 01" src="https://user-images.githubusercontent.com/10493229/40699283-6d457ee0-640e-11e8-9729-1f3e9a53deb3.png">
<img width="1038" alt="2018-05-30 1 35 49" src="https://user-images.githubusercontent.com/10493229/40699284-6d6edd94-640e-11e8-963e-669efb9cebd8.png">

**Comment by dattiren** [comment]
https://qiita.com/momoham/items/ee7bae955efec9db1a96
メンションを名前じゃなくてUserIDでやってみては？

**Comment by macinjoke** [comment]
やべ ↑のコメント全然気づいてなかった。今気づいた。

**Comment by macinjoke** [comment]
#4 で直しました。 close
